name: Zip and Commit
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  zip:
    if: contains(github.event.head_commit.message, 'zip-it')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create ZIP file
        run: |
          zip pdf2p2.zip \
            Parsedown.php \
            single-pdf2p2_gutenberg.php \
            minstral-send.php \
            single-pdf2p2_gutenberg.php \
            cpt-terms.php \
            cron.php \
            default-content.php \
            feed.php \
            import.php \
            logs.php \
            md-example.txt \
            md-gb.php \
            menu.php \
            pdf2p2-home.php \
            pdf2p2.php \
            minstral.php \
            pdf2p2-templates.php \
            settings.php \ 
            import_with_ocr.php

      - name: Commit ZIP file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pdf2p2.zip
          git commit -m "Update pdf2p2.zip on push to main" || echo "No changes to commit"
          git push
